version: '2'
services:
  solr:
    image: ebispot/ols-solr:latest
    environment:
      - SOLR_HOME=/mnt/solr-config
    ports:
      - ${MONGODB_IP}:8983:8983
    volumes:
      - ols-solr-data:/var/solr
      - ./ols-solr/src/main/solr-5-config:/mnt/solr-config
    command: ["-Dsolr.solr.home=/mnt/solr-config", "-Dsolr.data.dir=/var/solr", "-f"]
  mongo:
    image: mongo:3.2.9
    ports:
      - ${MONGODB_IP}:27017:27017
    volumes:
      - ols-mongo-data:/data/db
    command:
      - mongod
volumes:
  ols-solr-data:
    external: true
  ols-mongo-data:
    external: true